### ISSUE TITLE
Option to treat newlines as significant

### ISSUE THREAD

**Issue by jimthedev** [deanlandolt/deindent#1]
Hello hello. I have a use case where I need to de-indent but still want my newlines to be retained. 

So, the input might be:

```
    chore(logging): Adds verbose mode

    I added the following things to the app and it went really well

    Closes #4
```

And I'd like the output to be 

```
chore(logging): Adds verbose mode

I added the following things to the app and it went really well

Closes #4
```

In the current implementation, newlines between the lines are removed.

Would you consider an option to treat newlines as specific?

**Comment by deanlandolt** [comment]
I'd call that a bug -- the implementation was pretty much a direct translation of: https://gist.github.com/zenparsing/5dffde82d9acef19e43c -- but I've had the same issues with newlines.

I've been working on other stuff and haven't gotten back to the code that needed this, but I'll be revisiting it soonish and would need it to have the same behavior you spec'd. If you have the time to fix it in the meantime, go for it :)

**Comment by jimthedev** [comment]
@deanlandolt Thanks for the quick reply. I actually found [another package](https://github.com/dmnd/dedent) that seems to handle my usecase pretty well.  I am using the following pass a trusted `template` into the dd method, which then dedents properly.

``` js
var dedent = require('dedent');

function dd(str) {
  return dedent`${str}`;
}

// template is some artibrary string or es6 template string
dd(template); 
```

Thanks again.
